spring:
  application:
    name: dp

  profiles:
    active: dev   # ê¸°ë³¸ ì‹¤í–‰í™˜ê²½ì„ 'dev'ë¡œ ì„¤ì • (MySQL ì‚¬ìš©)

  # ================================
  # ğŸ§© ê³µí†µ ì„¤ì • (ëª¨ë“  í”„ë¡œí•„ ê³µìš©)
  # ================================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

# ================================
# ğŸ§© JWT ê³µí†µ ì„¤ì •
# ================================
jwt:
  secret: "abc123123abc123"

# ================================
# ğŸ§© DEV (MySQL - ë¡œì»¬ ê°œë°œ í™˜ê²½)
# ================================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: "jdbc:mysql://localhost:3306/club?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    username: "root"
    password: "@Ab86256653#"
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false

jwt:
  secret: "u283fh2hU93hf9283hF9283hf92hf983hf2h938hf293hf293hf"


# ================================
# ğŸ§© TEST (H2 - í…ŒìŠ¤íŠ¸ í™˜ê²½)
# ================================
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: "test-secret-key-123456"
